name: run python applicatin
on:
    pull_request:
        branches: [main]
    push:
        branches: [main, feat/gh-action-create ]

jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: run main
              run: python3 maint.py
