name: run python applicatin
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
