name: Run main.py on push and manually

on:
  push:  # Automatique sur chaque push
    branches:
      - feat/*
  workflow_dispatch:  # Manuel depuis l'onglet Actions

jobs:
  run-script:
    runs-on: ubuntu-latest
    outputs:
      my-output: ${{ steps.set-output-step.outputs.output }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main.py
        id: set-output-step
        run: |
          RESULT=$(python main.py)
          echo "output=$RESULT" >> $GITHUB_OUTPUT

  run-script2:
    needs: run-script
    runs-on: ubuntu-latest
    env: 
      RESULT: ${{ needs.run-script.outputs.my-output }}
    
    steps:
      - name: Echo resultat
        run: echo $RESULT


