# Changez le nom de workflow
name: CI with Environment Variables Arnaud

on:
  push:
    branches:
      - arnaud # Remplacez [branch-name] par le nom de votre branche
  workflow_dispatch:

# Ajoutez le variable global
env:
  GLOBAL_VAR: "Arnaud global variable"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    # Affichez le variable global 
    - name: Print global variable
      run: |
        echo "Global variable: $GLOBAL_VAR"

    # Ajoutez et affichez le variable local
    - name: Set and print local variable
      env:
        LOCAL_VAR: "Arnaud local variable"
      run: |
        echo "Local variable: $LOCAL_VAR"
    # Affichez le nom de branch
    - name: Print branch name
      run: |
        echo "Branch name: $GITHUB_REF_NAME"

    - name: Run Python script
      run: |
        python main.py